// server/services/daraja.service.js
const DARAJA_BASE_URL = "https://sandbox.safaricom.co.ke"; // switch to api.safaricom.co.ke for production

const CONSUMER_KEY = process.env.DARAJA_CONSUMER_KEY?.trim();
const CONSUMER_SECRET = process.env.DARAJA_CONSUMER_SECRET?.trim();
const SHORTCODE = process.env.DARAJA_SHORTCODE?.trim();
const PASSKEY = process.env.DARAJA_PASSKEY?.trim();
const CALLBACK_URL = process.env.DARAJA_CALLBACK_URL?.trim();

console.log("Daraja env check:", {
  key: CONSUMER_KEY ? `${CONSUMER_KEY.slice(0, 4)}...` : "MISSING",
  secret: CONSUMER_SECRET ? "set" : "MISSING",
  shortcode: SHORTCODE || "MISSING",
  passkey: PASSKEY ? "set" : "MISSING",
});

// ─── Phone format ────────────────────────────────────────────────────────────
// Members are stored as +2547XXXXXXXX, but Daraja wants 2547XXXXXXXX.
// Also handles 07XXXXXXXX and 7XXXXXXXX.
function formatPhone(phone) {
  let digits = String(phone).replace(/\D/g, "");
  if (digits.startsWith("0")) digits = "254" + digits.slice(1);
  else if (digits.length === 9) digits = "254" + digits;

  if (!/^254\d{9}$/.test(digits)) {
    throw new Error(`Invalid phone number: ${phone}`);
  }
  return digits;
}

// ─── OAuth access token ──────────────────────────────────────────────────────
// Daraja requires a short-lived OAuth token (valid ~1 hour) on every request.
// Generated by Basic-Auth-ing consumer key:secret against Daraja's OAuth
// endpoint. We fetch a fresh token per STK push rather than caching it, since
// contributions aren't frequent enough to justify a token cache.
async function getAccessToken() {
  const credentials = Buffer.from(`${CONSUMER_KEY}:${CONSUMER_SECRET}`).toString("base64");

  const response = await fetch(`${DARAJA_BASE_URL}/oauth/v1/generate?grant_type=client_credentials`, {
    method: "GET",
    headers: { Authorization: `Basic ${credentials}` },
  });

  // Read as text first so a non-JSON or empty response gives a clear error
  // instead of "Unexpected end of JSON input". We do NOT log the body on
  // success, because it contains the access token.
  const rawText = await response.text();

  let data;
  try {
    data = JSON.parse(rawText);
  } catch (err) {
    throw new Error(`Daraja OAuth returned non-JSON response (status ${response.status}): ${rawText.slice(0, 200)}`);
  }

  if (!data.access_token) {
    throw new Error(`Failed to get Daraja access token (status ${response.status}): ${rawText.slice(0, 200)}`);
  }

  return data.access_token;
}

// ─── Timestamp + Password ────────────────────────────────────────────────────
// Timestamp format is YYYYMMDDHHmmss. Password is base64(Shortcode + Passkey +
// Timestamp), which proves the request has your passkey without sending it.
function generateTimestamp() {
  const now = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return (
    now.getFullYear().toString() +
    pad(now.getMonth() + 1) +
    pad(now.getDate()) +
    pad(now.getHours()) +
    pad(now.getMinutes()) +
    pad(now.getSeconds())
  );
}

function generatePassword(timestamp) {
  return Buffer.from(`${SHORTCODE}${PASSKEY}${timestamp}`).toString("base64");
}

// ─── STK Push (Lipa na M-Pesa Online) ───────────────────────────────────────
// Triggers the real-time prompt on the member's phone. `amount` is in whole
// KSh (NOT cents). callbackUrl must be a public HTTPS URL (your ngrok URL +
// /api/daraja/callback). CheckoutRequestID is saved against the pending
// contribution row so the callback can match the result back to it.
async function initiateSTKPush({ phone, amount, accountReference, callbackUrl = CALLBACK_URL }) {
  if (!Number.isInteger(amount) || amount < 1) {
    throw new Error(`Amount must be a whole number of KSh, got: ${amount}`);
  }
  if (!callbackUrl) {
    throw new Error("No callback URL. Set DARAJA_CALLBACK_URL in .env");
  }

  const formattedPhone = formatPhone(phone);
  const accessToken = await getAccessToken();
  const timestamp = generateTimestamp();
  const password = generatePassword(timestamp);

  const response = await fetch(`${DARAJA_BASE_URL}/mpesa/stkpush/v1/processrequest`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      BusinessShortCode: SHORTCODE,
      Password: password,
      Timestamp: timestamp,
      TransactionType: "CustomerPayBillOnline",
      Amount: amount,
      PartyA: formattedPhone,
      PartyB: SHORTCODE,
      PhoneNumber: formattedPhone,
      CallBackURL: callbackUrl,
      AccountReference: String(accountReference).slice(0, 12), // Daraja limit: 12 chars
      TransactionDesc: "Chama savings", // Daraja limit: 13 chars
    }),
  });

  const rawText = await response.text();
  console.log("Daraja STK push response status:", response.status);
  console.log("Daraja STK push raw response:", rawText);

  let data;
  try {
    data = JSON.parse(rawText);
  } catch (err) {
    throw new Error(`Daraja STK push returned non-JSON response (status ${response.status}): ${rawText.slice(0, 200)}`);
  }

  if (data.ResponseCode !== "0") {
    throw new Error(data.errorMessage || data.ResponseDescription || "STK push failed");
  }

  return {
    checkoutRequestId: data.CheckoutRequestID,
    merchantRequestId: data.MerchantRequestID,
  };
}

module.exports = { initiateSTKPush, formatPhone };